#include "i2c.h"
/*


Each device must have an address
Serial Clock Generated by master device
Both wires connected to pull up resistors (and are open drain)
resistors 2K for 400 kbps


start condition sent (SDA low and clock high)

send address 7-bits
send read/write bit (1 read 0 write)
wait for ack, 0 on SDA
send slave's internal register address
wait for ack, 0 on SDA
send as much data as you like
wait for ack, 0 on SDA
stop (SDA rising edge, clock high)


*************************************************************************************


For avr

send start bit from TWCR
wait for TWINT bit in TWSR to be set
set TWINT bit to clear it in TWCR

load slave address and and read/write bit into TWDR and set appropriate bits in TWCR
wait for TWINT bit in TWSR to be set
set TWINT bit to clear it in TWCR

next block can be done multiple times
{
load data into TWDR and set appropriate bits in TWCR
wait for TWINT bit in TWSR to be set
set TWINT bit to clear it in TWCR
}


set appropriate bits in TWCR to send stop bit
wait for TWINT bit in TWSR to be set
set TWINT bit to clear it in TWCR
*/
void I2C_init(void)
{
    TWCR = (1 << TWEN);
}

void I2C_MasterTransmit(uint8 a_data, uint8 a_address)
{

    TWCR = (1 << TWINT) | (1 << TWSTA) | (1 << TWEN); /* Send START condition */

    while (!(TWCR & (1 << TWINT)))
        ;

    if ((TWSR & 0xF8) != MT_ST_SENT)
        // ERROR();

    TWDR = a_address | (1 << 7); // add write bit
    TWCR = (1 << TWINT) | (1 << TWEN);

    while (!(TWCR & (1 << TWINT)))
        ;
    if ((TWSR & 0xF8) != MT_SLA_ACK)
        // ERROR();

    TWDR = a_data;
    TWCR = (1 << TWINT) | (1 << TWEN);

    while (!(TWCR & (1 << TWINT)))
        ;

    if ((TWSR & 0xF8) != MT_DATA_ACK)
        // ERROR();

    // If repeated start is nedded
    // TWCR = (1 << TWINT) | (1 << TWSTA)| (1 << TWEN); /* Send START condition */
    // if ((TWSR & 0xF8) != MT_RST_SENT)
        // ERROR();

    TWCR = (1 << TWINT) | (1 << TWEN) | (1 << TWSTO);
}

uint8 I2C_receiveByte(uint8 *a_data, uint8 a_address)
{
    TWCR = (1 << TWINT) | (1 << TWSTA) | (1 << TWEN); /* Send START condition */

    while (!(TWCR & (1 << TWINT)))
        ;

    if ((TWSR & 0xF8) != MT_ST_SENT)
        // ERROR();

    TWDR = a_address & (~(1 << 7)); // add read bit
    TWCR = (1 << TWINT) | (1 << TWEN);

    while (!(TWCR & (1 << TWINT)))
        ;
    if ((TWSR & 0xF8) != MT_SLA_ACK)
        // ERROR();

    a_data = TWDR;
    TWCR = (1 << TWINT) | (1 << TWEN);

    // while (!(TWCR & (1 << TWINT)))
    //     ;

    // if ((TWSR & 0xF8) != MT_DATA_ACK)
        // ERROR();

    // If repeated start is nedded
    // TWCR = (1 << TWINT) | (1 << TWSTA)| (1 << TWEN); /* Send START condition */
    // if ((TWSR & 0xF8) != MT_RST_SENT)
        // ERROR();

    TWCR = (1 << TWINT) | (1 << TWEN) | (1 << TWSTO);
}

// void I2C_sendString(const uint8 *a_Str)
// {
//     uint32 i = 0;
//     while (a_Str[i] != '\0')
//     {
//         I2C_sendByte(a_Str[i++]);
//     }
//     I2C_sendByte('~');
// }

// void I2C_receiveString(uint8 *a_Str)
// {
//     uint8 i = 0;
//     uint8 c;
//     I2C_receiveByte(&c);
//     while (c != '~')
//     {
//         a_Str[i++] = c;
//         I2C_receiveByte(&c);
//     }
//     a_Str[--i] = '\0';
// }
